object Libs {
    const val ACTIVITY_KTX = "androidx.activity:activity-ktx"
    const val APPCOMPAT = "androidx.appcompat:appcompat"
    const val CONSTRAINT_LAYOUT = "androidx.constraintlayout:constraintlayout"
    const val CORE_KTX = "androidx.core:core-ktx"
    const val COROUTINES = "org.jetbrains.kotlinx:kotlinx-coroutines-android"
    const val ESPRESSO = "androidx.test.espresso:espresso-core"
    const val FIREBASE_AUTH = "com.google.firebase:firebase-auth-ktx"
    const val FIREBASE_BOM = "com.google.firebase:firebase-bom"
    const val GOOGLE_PLAY_SERVICES_AUTH = "com.google.android.gms:play-services-auth"
    const val JUNIT = "junit:junit"
    const val JUNIT_EXT = "androidx.test.ext:junit"
    const val LIFECYCLE_RUNTIME_KTX = "androidx.lifecycle:lifecycle-runtime-ktx"
    const val MATERIAL = "com.google.android.material:material"
    const val TIMBER = "com.jakewharton.timber:timber"
}