object Libs {
    const val ACTIVITY_COMPOSE = "androidx.activity:activity-compose"
    const val ACTIVITY_KTX = "androidx.activity:activity-ktx"
    const val APPCOMPAT = "androidx.appcompat:appcompat"
    const val BILLING = "com.android.billingclient:billing-ktx"
    const val COMPOSE_FOUNDATION = "androidx.compose.foundation:foundation"
    const val COMPOSE_FOUNDATION_LAYOUT = "androidx.compose.foundation:foundation-layout"
    const val COMPOSE_RUNTIME = "androidx.compose.runtime:runtime"
    const val COMPOSE_LIVEDATA = "androidx.compose.runtime:runtime-livedata"
    const val COMPOSE_MATERIAL = "androidx.compose.material:material"
    const val COMPOSE_THEME_ADAPTER = "com.google.android.material:compose-theme-adapter"
    const val COMPOSE_UI = "androidx.compose.ui:ui"
    const val COMPOSE_UI_TOOLING = "androidx.compose.ui:ui-tooling"
    const val CONSTRAINT_LAYOUT = "androidx.constraintlayout:constraintlayout"
    const val CORE_KTX = "androidx.core:core-ktx"
    const val COROUTINES = "org.jetbrains.kotlinx:kotlinx-coroutines-android"
    const val ESPRESSO = "androidx.test.espresso:espresso-core"
    const val FIREBASE_AUTH = "com.google.firebase:firebase-auth-ktx"
    const val FIREBASE_BOM = "com.google.firebase:firebase-bom"
    const val GOOGLE_PLAY_SERVICES_AUTH = "com.google.android.gms:play-services-auth"
    const val HILT_ANDROID = "com.google.dagger:hilt-android"
    const val HILT_COMPILER = "com.google.dagger:hilt-android-compiler"
    const val JUNIT = "junit:junit"
    const val JUNIT_EXT = "androidx.test.ext:junit"
    const val LIFECYCLE_RUNTIME_KTX = "androidx.lifecycle:lifecycle-runtime-ktx"
    const val MATERIAL = "com.google.android.material:material"
    const val TIMBER = "com.jakewharton.timber:timber"
    const val VIEWMODEL_COMPOSE = "androidx.lifecycle:lifecycle-viewmodel-compose"
}

object Plugins {
    const val ANDROID_GRADLE_PLUGIN = "com.android.tools.build:gradle"
    const val GOOGLE_SERVICES = "com.google.gms:google-services"
    const val HILT_AGP = "com.google.dagger:hilt-android-gradle-plugin"
    const val KOTLIN = "org.jetbrains.kotlin:kotlin-gradle-plugin"
}